/* automatically generated by rust-bindgen 0.72.1 */

#![allow(deprecated)]
use std::os::unix::raw::time_t;

pub type ZkByte = ::std::os::raw::c_uchar;
pub type ZkSize = ::std::os::raw::c_ulong;
pub type ZkOffset = ::std::os::raw::c_long;
pub type ZkBool = ::std::os::raw::c_uint;
pub type ZkString = *const ::std::os::raw::c_char;
pub type ZkStringEnumerator = ::std::option::Option<
    unsafe extern "C" fn(ctx: *mut ::std::os::raw::c_void, str_: ZkString) -> ZkBool,
>;
#[repr(u32)]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub enum ZkGameVersion {
    ZkGameVersion_GOTHIC1 = 0,
    ZkGameVersion_GOTHIC2 = 1,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct ZkInternal_Vec2 {
    pub x: f32,
    pub y: f32,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of ZkInternal_Vec2"][::std::mem::size_of::<ZkInternal_Vec2>() - 8usize];
    ["Alignment of ZkInternal_Vec2"][::std::mem::align_of::<ZkInternal_Vec2>() - 4usize];
    ["Offset of field: ZkInternal_Vec2::x"][::std::mem::offset_of!(ZkInternal_Vec2, x) - 0usize];
    ["Offset of field: ZkInternal_Vec2::y"][::std::mem::offset_of!(ZkInternal_Vec2, y) - 4usize];
};
pub type ZkVec2f = ZkInternal_Vec2;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct ZkInternal_Vec3 {
    pub x: f32,
    pub y: f32,
    pub z: f32,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of ZkInternal_Vec3"][::std::mem::size_of::<ZkInternal_Vec3>() - 12usize];
    ["Alignment of ZkInternal_Vec3"][::std::mem::align_of::<ZkInternal_Vec3>() - 4usize];
    ["Offset of field: ZkInternal_Vec3::x"][::std::mem::offset_of!(ZkInternal_Vec3, x) - 0usize];
    ["Offset of field: ZkInternal_Vec3::y"][::std::mem::offset_of!(ZkInternal_Vec3, y) - 4usize];
    ["Offset of field: ZkInternal_Vec3::z"][::std::mem::offset_of!(ZkInternal_Vec3, z) - 8usize];
};
pub type ZkVec3f = ZkInternal_Vec3;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct ZkInternal_Vec4 {
    pub x: f32,
    pub y: f32,
    pub z: f32,
    pub w: f32,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of ZkInternal_Vec4"][::std::mem::size_of::<ZkInternal_Vec4>() - 16usize];
    ["Alignment of ZkInternal_Vec4"][::std::mem::align_of::<ZkInternal_Vec4>() - 4usize];
    ["Offset of field: ZkInternal_Vec4::x"][::std::mem::offset_of!(ZkInternal_Vec4, x) - 0usize];
    ["Offset of field: ZkInternal_Vec4::y"][::std::mem::offset_of!(ZkInternal_Vec4, y) - 4usize];
    ["Offset of field: ZkInternal_Vec4::z"][::std::mem::offset_of!(ZkInternal_Vec4, z) - 8usize];
    ["Offset of field: ZkInternal_Vec4::w"][::std::mem::offset_of!(ZkInternal_Vec4, w) - 12usize];
};
pub type ZkVec4f = ZkInternal_Vec4;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct ZkInternal_Quat {
    pub x: f32,
    pub y: f32,
    pub z: f32,
    pub w: f32,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of ZkInternal_Quat"][::std::mem::size_of::<ZkInternal_Quat>() - 16usize];
    ["Alignment of ZkInternal_Quat"][::std::mem::align_of::<ZkInternal_Quat>() - 4usize];
    ["Offset of field: ZkInternal_Quat::x"][::std::mem::offset_of!(ZkInternal_Quat, x) - 0usize];
    ["Offset of field: ZkInternal_Quat::y"][::std::mem::offset_of!(ZkInternal_Quat, y) - 4usize];
    ["Offset of field: ZkInternal_Quat::z"][::std::mem::offset_of!(ZkInternal_Quat, z) - 8usize];
    ["Offset of field: ZkInternal_Quat::w"][::std::mem::offset_of!(ZkInternal_Quat, w) - 12usize];
};
pub type ZkQuat = ZkInternal_Quat;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct ZkInternal_Color {
    pub r: u8,
    pub g: u8,
    pub b: u8,
    pub a: u8,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of ZkInternal_Color"][::std::mem::size_of::<ZkInternal_Color>() - 4usize];
    ["Alignment of ZkInternal_Color"][::std::mem::align_of::<ZkInternal_Color>() - 1usize];
    ["Offset of field: ZkInternal_Color::r"][::std::mem::offset_of!(ZkInternal_Color, r) - 0usize];
    ["Offset of field: ZkInternal_Color::g"][::std::mem::offset_of!(ZkInternal_Color, g) - 1usize];
    ["Offset of field: ZkInternal_Color::b"][::std::mem::offset_of!(ZkInternal_Color, b) - 2usize];
    ["Offset of field: ZkInternal_Color::a"][::std::mem::offset_of!(ZkInternal_Color, a) - 3usize];
};
pub type ZkColor = ZkInternal_Color;
pub type ZkVec2fEnumerator = ::std::option::Option<
    unsafe extern "C" fn(ctx: *mut ::std::os::raw::c_void, v: ZkVec2f) -> ZkBool,
>;
pub type ZkVec3fEnumerator = ::std::option::Option<
    unsafe extern "C" fn(ctx: *mut ::std::os::raw::c_void, v: ZkVec3f) -> ZkBool,
>;
pub type ZkVec4fEnumerator = ::std::option::Option<
    unsafe extern "C" fn(ctx: *mut ::std::os::raw::c_void, v: ZkVec4f) -> ZkBool,
>;
pub type ZkQuatEnumerator = ::std::option::Option<
    unsafe extern "C" fn(ctx: *mut ::std::os::raw::c_void, v: ZkQuat) -> ZkBool,
>;
pub type ZkColorEnumerator = ::std::option::Option<
    unsafe extern "C" fn(ctx: *mut ::std::os::raw::c_void, v: ZkColor) -> ZkBool,
>;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct ZkInternal_OrientedBoundingBox {
    _unused: [u8; 0],
}
pub type ZkOrientedBoundingBox = ZkInternal_OrientedBoundingBox;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct ZkInternal_AxisAlignedBoundingBox {
    pub min: ZkVec3f,
    pub max: ZkVec3f,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of ZkInternal_AxisAlignedBoundingBox"]
        [::std::mem::size_of::<ZkInternal_AxisAlignedBoundingBox>() - 24usize];
    ["Alignment of ZkInternal_AxisAlignedBoundingBox"]
        [::std::mem::align_of::<ZkInternal_AxisAlignedBoundingBox>() - 4usize];
    ["Offset of field: ZkInternal_AxisAlignedBoundingBox::min"]
        [::std::mem::offset_of!(ZkInternal_AxisAlignedBoundingBox, min) - 0usize];
    ["Offset of field: ZkInternal_AxisAlignedBoundingBox::max"]
        [::std::mem::offset_of!(ZkInternal_AxisAlignedBoundingBox, max) - 12usize];
};
pub type ZkAxisAlignedBoundingBox = ZkInternal_AxisAlignedBoundingBox;
pub type ZkOrientedBoundingBoxEnumerator = ::std::option::Option<
    unsafe extern "C" fn(
        arg1: *mut ::std::os::raw::c_void,
        box_: *const ZkOrientedBoundingBox,
    ) -> ZkBool,
>;
unsafe extern "C" {
    pub fn ZkOrientedBoundingBox_getCenter(slf: *const ZkOrientedBoundingBox) -> ZkVec3f;
}
unsafe extern "C" {
    pub fn ZkOrientedBoundingBox_getAxis(slf: *const ZkOrientedBoundingBox, i: ZkSize) -> ZkVec3f;
}
unsafe extern "C" {
    pub fn ZkOrientedBoundingBox_getHalfWidth(slf: *const ZkOrientedBoundingBox) -> ZkVec3f;
}
unsafe extern "C" {
    pub fn ZkOrientedBoundingBox_getChildCount(slf: *const ZkOrientedBoundingBox) -> ZkSize;
}
unsafe extern "C" {
    pub fn ZkOrientedBoundingBox_getChild(
        slf: *const ZkOrientedBoundingBox,
        i: ZkSize,
    ) -> *const ZkOrientedBoundingBox;
}
unsafe extern "C" {
    pub fn ZkOrientedBoundingBox_enumerateChildren(
        slf: *const ZkOrientedBoundingBox,
        cb: ZkOrientedBoundingBoxEnumerator,
        ctx: *mut ::std::os::raw::c_void,
    );
}
unsafe extern "C" {
    pub fn ZkOrientedBoundingBox_toAabb(
        slf: *const ZkOrientedBoundingBox,
    ) -> ZkAxisAlignedBoundingBox;
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct ZkDate {
    pub year: u32,
    pub month: u16,
    pub day: u16,
    pub hour: u16,
    pub minute: u16,
    pub second: u16,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of ZkDate"][::std::mem::size_of::<ZkDate>() - 16usize];
    ["Alignment of ZkDate"][::std::mem::align_of::<ZkDate>() - 4usize];
    ["Offset of field: ZkDate::year"][::std::mem::offset_of!(ZkDate, year) - 0usize];
    ["Offset of field: ZkDate::month"][::std::mem::offset_of!(ZkDate, month) - 4usize];
    ["Offset of field: ZkDate::day"][::std::mem::offset_of!(ZkDate, day) - 6usize];
    ["Offset of field: ZkDate::hour"][::std::mem::offset_of!(ZkDate, hour) - 8usize];
    ["Offset of field: ZkDate::minute"][::std::mem::offset_of!(ZkDate, minute) - 10usize];
    ["Offset of field: ZkDate::second"][::std::mem::offset_of!(ZkDate, second) - 12usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct ZkInternal_Read {
    _unused: [u8; 0],
}
pub type ZkRead = ZkInternal_Read;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct ZkInternal_Write {
    _unused: [u8; 0],
}
pub type ZkWrite = ZkInternal_Write;
#[repr(u32)]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub enum ZkWhence {
    ZK_BEG = 0,
    ZKC_UR = 1,
    ZK_END = 2,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct ZkReadExt {
    pub read: ::std::option::Option<
        unsafe extern "C" fn(
            ctx: *mut ::std::os::raw::c_void,
            buf: *mut ::std::os::raw::c_void,
            len: ZkSize,
        ) -> ZkSize,
    >,
    pub seek: ::std::option::Option<
        unsafe extern "C" fn(
            ctx: *mut ::std::os::raw::c_void,
            off: ZkOffset,
            whence: ZkWhence,
        ) -> ZkSize,
    >,
    pub tell:
        ::std::option::Option<unsafe extern "C" fn(ctx: *const ::std::os::raw::c_void) -> ZkSize>,
    pub eof:
        ::std::option::Option<unsafe extern "C" fn(ctx: *const ::std::os::raw::c_void) -> ZkBool>,
    pub del: ::std::option::Option<unsafe extern "C" fn(ctx: *const ::std::os::raw::c_void)>,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of ZkReadExt"][::std::mem::size_of::<ZkReadExt>() - 40usize];
    ["Alignment of ZkReadExt"][::std::mem::align_of::<ZkReadExt>() - 8usize];
    ["Offset of field: ZkReadExt::read"][::std::mem::offset_of!(ZkReadExt, read) - 0usize];
    ["Offset of field: ZkReadExt::seek"][::std::mem::offset_of!(ZkReadExt, seek) - 8usize];
    ["Offset of field: ZkReadExt::tell"][::std::mem::offset_of!(ZkReadExt, tell) - 16usize];
    ["Offset of field: ZkReadExt::eof"][::std::mem::offset_of!(ZkReadExt, eof) - 24usize];
    ["Offset of field: ZkReadExt::del"][::std::mem::offset_of!(ZkReadExt, del) - 32usize];
};
unsafe extern "C" {
    pub fn ZkRead_newMem(bytes: *const ZkByte, length: ZkSize) -> *mut ZkRead;
}
unsafe extern "C" {
    pub fn ZkRead_newPath(path: ZkString) -> *mut ZkRead;
}
unsafe extern "C" {
    pub fn ZkRead_newExt(ext: ZkReadExt, ctx: *mut ::std::os::raw::c_void) -> *mut ZkRead;
}
unsafe extern "C" {
    pub fn ZkRead_del(slf: *mut ZkRead);
}
unsafe extern "C" {
    pub fn ZkRead_getSize(slf: *mut ZkRead) -> ZkSize;
}
unsafe extern "C" {
    pub fn ZkRead_getBytes(
        slf: *mut ZkRead,
        buf: *mut ::std::os::raw::c_void,
        length: ZkSize,
    ) -> ZkSize;
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct ZkWriteExt {
    pub write: ::std::option::Option<
        unsafe extern "C" fn(
            ctx: *mut ::std::os::raw::c_void,
            buf: *const ::std::os::raw::c_void,
            len: ZkSize,
        ) -> ZkSize,
    >,
    pub seek: ::std::option::Option<
        unsafe extern "C" fn(
            ctx: *mut ::std::os::raw::c_void,
            off: ZkOffset,
            whence: ZkWhence,
        ) -> ZkSize,
    >,
    pub tell:
        ::std::option::Option<unsafe extern "C" fn(ctx: *const ::std::os::raw::c_void) -> ZkSize>,
    pub del: ::std::option::Option<unsafe extern "C" fn(ctx: *const ::std::os::raw::c_void)>,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of ZkWriteExt"][::std::mem::size_of::<ZkWriteExt>() - 32usize];
    ["Alignment of ZkWriteExt"][::std::mem::align_of::<ZkWriteExt>() - 8usize];
    ["Offset of field: ZkWriteExt::write"][::std::mem::offset_of!(ZkWriteExt, write) - 0usize];
    ["Offset of field: ZkWriteExt::seek"][::std::mem::offset_of!(ZkWriteExt, seek) - 8usize];
    ["Offset of field: ZkWriteExt::tell"][::std::mem::offset_of!(ZkWriteExt, tell) - 16usize];
    ["Offset of field: ZkWriteExt::del"][::std::mem::offset_of!(ZkWriteExt, del) - 24usize];
};
unsafe extern "C" {
    pub fn ZkWrite_newMem(bytes: *mut ZkByte, length: ZkSize) -> *mut ZkWrite;
}
unsafe extern "C" {
    pub fn ZkWrite_newPath(path: ZkString) -> *mut ZkWrite;
}
unsafe extern "C" {
    pub fn ZkWrite_newExt(ext: ZkWriteExt, ctx: *mut ::std::os::raw::c_void) -> *mut ZkWrite;
}
unsafe extern "C" {
    pub fn ZkWrite_del(slf: *mut ZkWrite);
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct ZkInternal_Material {
    _unused: [u8; 0],
}
pub type ZkMaterial = ZkInternal_Material;
#[repr(u32)]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub enum ZkMaterialGroup {
    ZkMaterialGroup_UNDEFINED = 0,
    ZkMaterialGroup_METAL = 1,
    ZkMaterialGroup_STONE = 2,
    ZkMaterialGroup_WOOD = 3,
    ZkMaterialGroup_EARTH = 4,
    ZkMaterialGroup_WATER = 5,
    ZkMaterialGroup_SNOW = 6,
}
#[repr(u32)]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub enum ZkAnimationMapping {
    ZkAnimationMapping_NONE = 0,
    ZkAnimationMapping_LINEAR = 1,
}
#[repr(u32)]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub enum ZkWaveMode {
    ZkWaveMode_NONE = 0,
    ZkWaveMode_GROUND_AMBIENT = 1,
    ZkWaveMode_GROUND = 2,
    ZkWaveMode_WALL_AMBIENT = 3,
    ZkWaveMode_WALL = 4,
    ZkWaveMode_ENVIRONMENT = 5,
    ZkWaveMode_WIND_AMBIENT = 6,
    ZkWaveMode_WIND = 7,
}
#[repr(u32)]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub enum ZkWaveSpeed {
    ZkWaveSpeed_NONE = 0,
    ZkWaveSpeed_SLOW = 1,
    ZkWaveSpeed_NORMAL = 2,
    ZkWaveSpeed_FAST = 3,
}
#[repr(u32)]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub enum ZkAlphaFunction {
    ZkAlphaFunction_DEFAULT = 0,
    ZkAlphaFunction_NONE = 1,
    ZkAlphaFunction_BLEND = 2,
    ZkAlphaFunction_ADD = 3,
    ZkAlphaFunction_SUBTRACT = 4,
    ZkAlphaFunction_MULTIPLY = 5,
    ZkAlphaFunction_MULTIPLY_ALT = 6,
}
pub type ZkMaterialEnumerator = ::std::option::Option<
    unsafe extern "C" fn(ctx: *mut ::std::os::raw::c_void, material: *const ZkMaterial) -> ZkBool,
>;
unsafe extern "C" {
    pub fn ZkMaterial_load(buf: *mut ZkRead) -> *mut ZkMaterial;
}
unsafe extern "C" {
    pub fn ZkMaterial_loadPath(path: ZkString) -> *mut ZkMaterial;
}
unsafe extern "C" {
    pub fn ZkMaterial_del(slf: *mut ZkMaterial);
}
unsafe extern "C" {
    pub fn ZkMaterial_getName(slf: *const ZkMaterial) -> ZkString;
}
unsafe extern "C" {
    pub fn ZkMaterial_getGroup(slf: *const ZkMaterial) -> ZkMaterialGroup;
}
unsafe extern "C" {
    pub fn ZkMaterial_getColor(slf: *const ZkMaterial) -> ZkColor;
}
unsafe extern "C" {
    pub fn ZkMaterial_getSmoothAngle(slf: *const ZkMaterial) -> f32;
}
unsafe extern "C" {
    pub fn ZkMaterial_getTexture(slf: *const ZkMaterial) -> ZkString;
}
unsafe extern "C" {
    pub fn ZkMaterial_getTextureScale(slf: *const ZkMaterial) -> ZkVec2f;
}
unsafe extern "C" {
    pub fn ZkMaterial_getTextureAnimationFps(slf: *const ZkMaterial) -> f32;
}
unsafe extern "C" {
    pub fn ZkMaterial_getTextureAnimationMapping(slf: *const ZkMaterial) -> ZkAnimationMapping;
}
unsafe extern "C" {
    pub fn ZkMaterial_getTextureAnimationMappingDirection(slf: *const ZkMaterial) -> ZkVec2f;
}
unsafe extern "C" {
    pub fn ZkMaterial_getDisableCollision(slf: *const ZkMaterial) -> ZkBool;
}
unsafe extern "C" {
    pub fn ZkMaterial_getDisableLightmap(slf: *const ZkMaterial) -> ZkBool;
}
unsafe extern "C" {
    pub fn ZkMaterial_getDontCollapse(slf: *const ZkMaterial) -> ZkBool;
}
unsafe extern "C" {
    pub fn ZkMaterial_getDetailObject(slf: *const ZkMaterial) -> ZkString;
}
unsafe extern "C" {
    pub fn ZkMaterial_getDetailObjectScale(slf: *const ZkMaterial) -> f32;
}
unsafe extern "C" {
    pub fn ZkMaterial_getForceOccluder(slf: *const ZkMaterial) -> ZkBool;
}
unsafe extern "C" {
    pub fn ZkMaterial_getEnvironmentMapping(slf: *const ZkMaterial) -> ZkBool;
}
unsafe extern "C" {
    pub fn ZkMaterial_getEnvironmentMappingStrength(slf: *const ZkMaterial) -> f32;
}
unsafe extern "C" {
    pub fn ZkMaterial_getWaveMode(slf: *const ZkMaterial) -> ZkWaveMode;
}
unsafe extern "C" {
    pub fn ZkMaterial_getWaveSpeed(slf: *const ZkMaterial) -> ZkWaveSpeed;
}
unsafe extern "C" {
    pub fn ZkMaterial_getWaveAmplitude(slf: *const ZkMaterial) -> f32;
}
unsafe extern "C" {
    pub fn ZkMaterial_getWaveGridSize(slf: *const ZkMaterial) -> f32;
}
unsafe extern "C" {
    pub fn ZkMaterial_getIgnoreSun(slf: *const ZkMaterial) -> ZkBool;
}
unsafe extern "C" {
    pub fn ZkMaterial_getAlphaFunction(slf: *const ZkMaterial) -> ZkAlphaFunction;
}
unsafe extern "C" {
    pub fn ZkMaterial_getDefaultMapping(slf: *const ZkMaterial) -> ZkVec2f;
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct ZkInternal_Vfs {
    _unused: [u8; 0],
}
pub type ZkVfs = ZkInternal_Vfs;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct ZkInternal_VfsNode {
    _unused: [u8; 0],
}
pub type ZkVfsNode = ZkInternal_VfsNode;
#[repr(u32)]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub enum ZkVfsOverwriteBehavior {
    ZkVfsOverwriteBehavior_NONE = 0,
    ZkVfsOverwriteBehavior_ALL = 1,
    ZkVfsOverwriteBehavior_NEWER = 2,
    ZkVfsOverwriteBehavior_OLDER = 3,
}
pub type ZkVfsNodeEnumerator = ::std::option::Option<
    unsafe extern "C" fn(ctx: *mut ::std::os::raw::c_void, node: *const ZkVfsNode) -> ZkBool,
>;
unsafe extern "C" {
    pub fn ZkVfs_new() -> *mut ZkVfs;
}
unsafe extern "C" {
    pub fn ZkVfs_del(slf: *mut ZkVfs);
}
unsafe extern "C" {
    pub fn ZkVfs_save(slf: *const ZkVfs, path: ZkString, version: ZkGameVersion, unix_t: time_t);
}
unsafe extern "C" {
    pub fn ZkVfs_getRoot(slf: *const ZkVfs) -> *const ZkVfsNode;
}
unsafe extern "C" {
    pub fn ZkVfs_mkdir(slf: *mut ZkVfs, path: ZkString) -> *mut ZkVfsNode;
}
unsafe extern "C" {
    pub fn ZkVfs_remove(slf: *mut ZkVfs, path: ZkString) -> ZkBool;
}
unsafe extern "C" {
    pub fn ZkVfs_mount(
        slf: *mut ZkVfs,
        node: *mut ZkVfsNode,
        parent: ZkString,
        overwrite: ZkVfsOverwriteBehavior,
    );
}
unsafe extern "C" {
    pub fn ZkVfs_mountHost(
        slf: *mut ZkVfs,
        path: ZkString,
        parent: ZkString,
        overwrite: ZkVfsOverwriteBehavior,
    );
}
unsafe extern "C" {
    pub fn ZkVfs_mountDisk(slf: *mut ZkVfs, buf: *mut ZkRead, overwrite: ZkVfsOverwriteBehavior);
}
unsafe extern "C" {
    pub fn ZkVfs_mountDiskHost(slf: *mut ZkVfs, path: ZkString, overwrite: ZkVfsOverwriteBehavior);
}
unsafe extern "C" {
    pub fn ZkVfs_resolvePath(slf: *mut ZkVfs, path: ZkString) -> *mut ZkVfsNode;
}
unsafe extern "C" {
    pub fn ZkVfs_findNode(slf: *mut ZkVfs, name: ZkString) -> *mut ZkVfsNode;
}
unsafe extern "C" {
    pub fn ZkVfsNode_newFile(
        name: ZkString,
        buf: *const ZkByte,
        size: ZkSize,
        ts: time_t,
    ) -> *mut ZkVfsNode;
}
unsafe extern "C" {
    pub fn ZkVfsNode_newDir(name: ZkString, ts: time_t) -> *mut ZkVfsNode;
}
unsafe extern "C" {
    pub fn ZkVfsNode_del(slf: *mut ZkVfsNode);
}
unsafe extern "C" {
    pub fn ZkVfsNode_isFile(slf: *const ZkVfsNode) -> ZkBool;
}
unsafe extern "C" {
    pub fn ZkVfsNode_isDir(slf: *const ZkVfsNode) -> ZkBool;
}
unsafe extern "C" {
    pub fn ZkVfsNode_getTime(slf: *const ZkVfsNode) -> time_t;
}
unsafe extern "C" {
    pub fn ZkVfsNode_getName(slf: *const ZkVfsNode) -> ZkString;
}
unsafe extern "C" {
    pub fn ZkVfsNode_getChild(slf: *mut ZkVfsNode, name: ZkString) -> *mut ZkVfsNode;
}
unsafe extern "C" {
    pub fn ZkVfsNode_create(slf: *mut ZkVfsNode, node: *mut ZkVfsNode) -> *mut ZkVfsNode;
}
unsafe extern "C" {
    pub fn ZkVfsNode_remove(slf: *mut ZkVfsNode, name: ZkString) -> ZkBool;
}
unsafe extern "C" {
    pub fn ZkVfsNode_open(slf: *const ZkVfsNode) -> *mut ZkRead;
}
unsafe extern "C" {
    pub fn ZkVfsNode_enumerateChildren(
        slf: *const ZkVfsNode,
        callback: ZkVfsNodeEnumerator,
        ctx: *mut ::std::os::raw::c_void,
    );
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct ZkInternal_Texture {
    _unused: [u8; 0],
}
pub type ZkTexture = ZkInternal_Texture;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct ZkInternal_TextureBuilder {
    _unused: [u8; 0],
}
pub type ZkTextureBuilder = ZkInternal_TextureBuilder;
#[repr(u32)]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub enum ZkTextureFormat {
    ZkTextureFormat_B8G8R8A8 = 0,
    ZkTextureFormat_R8G8B8A8 = 1,
    ZkTextureFormat_A8B8G8R8 = 2,
    ZkTextureFormat_A8R8G8B8 = 3,
    ZkTextureFormat_B8G8R8 = 4,
    ZkTextureFormat_R8G8B8 = 5,
    ZkTextureFormat_A4R4G4B4 = 6,
    ZkTextureFormat_A1R5G5B5 = 7,
    ZkTextureFormat_R5G6B5 = 8,
    ZkTextureFormat_P8 = 9,
    ZkTextureFormat_DXT1 = 10,
    ZkTextureFormat_DXT2 = 11,
    ZkTextureFormat_DXT3 = 12,
    ZkTextureFormat_DXT4 = 13,
    ZkTextureFormat_DXT5 = 14,
}
pub type ZkTextureMipmapEnumerator = ::std::option::Option<
    unsafe extern "C" fn(
        ctx: *mut ::std::os::raw::c_void,
        level: ZkSize,
        data: *const u8,
        size: ZkSize,
    ) -> ZkBool,
>;
unsafe extern "C" {
    pub fn ZkTexture_load(buf: *mut ZkRead) -> *mut ZkTexture;
}
unsafe extern "C" {
    pub fn ZkTexture_loadPath(path: ZkString) -> *mut ZkTexture;
}
unsafe extern "C" {
    pub fn ZkTexture_loadVfs(vfs: *mut ZkVfs, name: ZkString) -> *mut ZkTexture;
}
unsafe extern "C" {
    pub fn ZkTexture_del(slf: *mut ZkTexture);
}
unsafe extern "C" {
    pub fn ZkTexture_getFormat(slf: *const ZkTexture) -> ZkTextureFormat;
}
unsafe extern "C" {
    pub fn ZkTexture_getWidth(slf: *const ZkTexture) -> u32;
}
unsafe extern "C" {
    pub fn ZkTexture_getHeight(slf: *const ZkTexture) -> u32;
}
unsafe extern "C" {
    pub fn ZkTexture_getWidthMipmap(slf: *const ZkTexture, level: ZkSize) -> u32;
}
unsafe extern "C" {
    pub fn ZkTexture_getHeightMipmap(slf: *const ZkTexture, level: ZkSize) -> u32;
}
unsafe extern "C" {
    pub fn ZkTexture_getWidthRef(slf: *const ZkTexture) -> u32;
}
unsafe extern "C" {
    pub fn ZkTexture_getHeightRef(slf: *const ZkTexture) -> u32;
}
unsafe extern "C" {
    pub fn ZkTexture_getMipmapCount(slf: *const ZkTexture) -> u32;
}
unsafe extern "C" {
    pub fn ZkTexture_getAverageColor(slf: *const ZkTexture) -> u32;
}
unsafe extern "C" {
    pub fn ZkTexture_getPaletteSize(slf: *const ZkTexture) -> ZkSize;
}
unsafe extern "C" {
    pub fn ZkTexture_getPaletteItem(slf: *const ZkTexture, i: ZkSize) -> ZkColor;
}
unsafe extern "C" {
    pub fn ZkTexture_enumeratePaletteItems(
        slf: *const ZkTexture,
        cb: ZkColorEnumerator,
        ctx: *mut ::std::os::raw::c_void,
    );
}
unsafe extern "C" {
    pub fn ZkTexture_getMipmapRaw(
        slf: *const ZkTexture,
        level: ZkSize,
        size: *mut ZkSize,
    ) -> *const u8;
}
unsafe extern "C" {
    pub fn ZkTexture_getMipmapRgba(
        slf: *const ZkTexture,
        level: ZkSize,
        buf: *mut u8,
        size: ZkSize,
    ) -> ZkSize;
}
unsafe extern "C" {
    pub fn ZkTexture_enumerateRawMipmaps(
        slf: *const ZkTexture,
        cb: ZkTextureMipmapEnumerator,
        ctx: *mut ::std::os::raw::c_void,
    );
}
unsafe extern "C" {
    pub fn ZkTexture_enumerateRgbaMipmaps(
        slf: *const ZkTexture,
        cb: ZkTextureMipmapEnumerator,
        ctx: *mut ::std::os::raw::c_void,
    );
}
unsafe extern "C" {
    pub fn ZkTextureBuilder_new(width: ZkSize, height: ZkSize) -> *mut ZkTextureBuilder;
}
unsafe extern "C" {
    pub fn ZkTextureBuilder_del(slf: *mut ZkTextureBuilder);
}
unsafe extern "C" {
    pub fn ZkTextureBuilder_addMipmap(
        slf: *mut ZkTextureBuilder,
        buf: *mut ZkByte,
        len: ZkSize,
        fmt: ZkTextureFormat,
    ) -> ZkBool;
}
unsafe extern "C" {
    pub fn ZkTextureBuilder_build(
        slf: *mut ZkTextureBuilder,
        fmt: ZkTextureFormat,
    ) -> *mut ZkTexture;
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct ZkInternal_Mesh {
    _unused: [u8; 0],
}
pub type ZkMesh = ZkInternal_Mesh;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct ZkInternal_LightMap {
    _unused: [u8; 0],
}
pub type ZkLightMap = ZkInternal_LightMap;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct ZkInternal_Polygon {
    _unused: [u8; 0],
}
pub type ZkPolygon = ZkInternal_Polygon;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct ZkInternal_Vertex {
    pub texture: ZkVec2f,
    pub light: u32,
    pub normal: ZkVec3f,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of ZkInternal_Vertex"][::std::mem::size_of::<ZkInternal_Vertex>() - 24usize];
    ["Alignment of ZkInternal_Vertex"][::std::mem::align_of::<ZkInternal_Vertex>() - 4usize];
    ["Offset of field: ZkInternal_Vertex::texture"]
        [::std::mem::offset_of!(ZkInternal_Vertex, texture) - 0usize];
    ["Offset of field: ZkInternal_Vertex::light"]
        [::std::mem::offset_of!(ZkInternal_Vertex, light) - 8usize];
    ["Offset of field: ZkInternal_Vertex::normal"]
        [::std::mem::offset_of!(ZkInternal_Vertex, normal) - 12usize];
};
pub type ZkVertex = ZkInternal_Vertex;
pub type ZkVertexEnumerator = ::std::option::Option<
    unsafe extern "C" fn(ctx: *mut ::std::os::raw::c_void, vertex: *mut ZkVertex) -> ZkBool,
>;
pub type ZkLightMapEnumerator = ::std::option::Option<
    unsafe extern "C" fn(ctx: *mut ::std::os::raw::c_void, lightMap: *const ZkLightMap) -> ZkBool,
>;
pub type ZkPolygonEnumerator = ::std::option::Option<
    unsafe extern "C" fn(ctx: *mut ::std::os::raw::c_void, polygon: *const ZkPolygon) -> ZkBool,
>;
unsafe extern "C" {
    pub fn ZkMesh_load(buf: *mut ZkRead) -> *mut ZkMesh;
}
unsafe extern "C" {
    pub fn ZkMesh_loadPath(path: ZkString) -> *mut ZkMesh;
}
unsafe extern "C" {
    pub fn ZkMesh_loadVfs(vfs: *mut ZkVfs, name: ZkString) -> *mut ZkMesh;
}
unsafe extern "C" {
    pub fn ZkMesh_del(slf: *mut ZkMesh);
}
unsafe extern "C" {
    pub fn ZkMesh_getSourceDate(slf: *const ZkMesh) -> ZkDate;
}
unsafe extern "C" {
    pub fn ZkMesh_getName(slf: *const ZkMesh) -> ZkString;
}
unsafe extern "C" {
    pub fn ZkMesh_getBoundingBox(slf: *const ZkMesh) -> ZkAxisAlignedBoundingBox;
}
unsafe extern "C" {
    pub fn ZkMesh_getOrientedBoundingBox(slf: *const ZkMesh) -> *const ZkOrientedBoundingBox;
}
unsafe extern "C" {
    pub fn ZkMesh_getMaterialCount(slf: *const ZkMesh) -> ZkSize;
}
unsafe extern "C" {
    pub fn ZkMesh_getMaterial(slf: *const ZkMesh, i: ZkSize) -> *const ZkMaterial;
}
unsafe extern "C" {
    pub fn ZkMesh_enumerateMaterials(
        slf: *const ZkMesh,
        cb: ZkMaterialEnumerator,
        ctx: *mut ::std::os::raw::c_void,
    );
}
unsafe extern "C" {
    pub fn ZkMesh_getPositionCount(slf: *const ZkMesh) -> ZkSize;
}
unsafe extern "C" {
    pub fn ZkMesh_getPosition(slf: *const ZkMesh, i: ZkSize) -> ZkVec3f;
}
unsafe extern "C" {
    pub fn ZkMesh_enumeratePositions(
        slf: *const ZkMesh,
        cb: ZkVec3fEnumerator,
        ctx: *mut ::std::os::raw::c_void,
    );
}
unsafe extern "C" {
    pub fn ZkMesh_getVertexCount(slf: *const ZkMesh) -> ZkSize;
}
unsafe extern "C" {
    pub fn ZkMesh_getVertex(slf: *const ZkMesh, i: ZkSize) -> ZkVertex;
}
unsafe extern "C" {
    pub fn ZkMesh_enumerateVertices(
        slf: *const ZkMesh,
        cb: ZkVertexEnumerator,
        ctx: *mut ::std::os::raw::c_void,
    );
}
unsafe extern "C" {
    pub fn ZkMesh_getLightMapCount(slf: *const ZkMesh) -> ZkSize;
}
unsafe extern "C" {
    pub fn ZkMesh_getLightMap(slf: *const ZkMesh, i: ZkSize) -> *const ZkLightMap;
}
unsafe extern "C" {
    pub fn ZkMesh_enumerateLightMaps(
        slf: *const ZkMesh,
        cb: ZkLightMapEnumerator,
        ctx: *mut ::std::os::raw::c_void,
    );
}
unsafe extern "C" {
    pub fn ZkMesh_getPolygonCount(slf: *const ZkMesh) -> ZkSize;
}
unsafe extern "C" {
    pub fn ZkMesh_getPolygon(slf: *const ZkMesh, i: ZkSize) -> *const ZkPolygon;
}
unsafe extern "C" {
    pub fn ZkMesh_enumeratePolygons(
        slf: *const ZkMesh,
        cb: ZkPolygonEnumerator,
        ctx: *mut ::std::os::raw::c_void,
    );
}
unsafe extern "C" {
    pub fn ZkLightMap_getImage(slf: *const ZkLightMap) -> *const ZkTexture;
}
unsafe extern "C" {
    pub fn ZkLightMap_getOrigin(slf: *const ZkLightMap) -> ZkVec3f;
}
unsafe extern "C" {
    pub fn ZkLightMap_getNormal(slf: *const ZkLightMap, i: ZkSize) -> ZkVec3f;
}
unsafe extern "C" {
    pub fn ZkPolygon_getMaterialIndex(slf: *const ZkPolygon) -> u32;
}
unsafe extern "C" {
    pub fn ZkPolygon_getLightMapIndex(slf: *const ZkPolygon) -> i32;
}
unsafe extern "C" {
    pub fn ZkPolygon_getPositionIndices(
        slf: *const ZkPolygon,
        msh: *const ZkMesh,
        count: *mut ZkSize,
    ) -> *const u32;
}
unsafe extern "C" {
    pub fn ZkPolygon_getFeatureIndices(
        slf: *const ZkPolygon,
        msh: *const ZkMesh,
        count: *mut ZkSize,
    ) -> *const u32;
}
unsafe extern "C" {
    pub fn ZkPolygon_getIsPortal(slf: *const ZkPolygon) -> ZkBool;
}
unsafe extern "C" {
    pub fn ZkPolygon_getIsOccluder(slf: *const ZkPolygon) -> ZkBool;
}
unsafe extern "C" {
    pub fn ZkPolygon_getIsSector(slf: *const ZkPolygon) -> ZkBool;
}
unsafe extern "C" {
    pub fn ZkPolygon_getShouldRelight(slf: *const ZkPolygon) -> ZkBool;
}
unsafe extern "C" {
    pub fn ZkPolygon_getIsOutdoor(slf: *const ZkPolygon) -> ZkBool;
}
unsafe extern "C" {
    pub fn ZkPolygon_getIsGhostOccluder(slf: *const ZkPolygon) -> ZkBool;
}
unsafe extern "C" {
    pub fn ZkPolygon_getIsDynamicallyLit(slf: *const ZkPolygon) -> ZkBool;
}
unsafe extern "C" {
    pub fn ZkPolygon_getIsLod(slf: *const ZkPolygon) -> ZkBool;
}
unsafe extern "C" {
    pub fn ZkPolygon_getNormalAxis(slf: *const ZkPolygon) -> u8;
}
unsafe extern "C" {
    pub fn ZkPolygon_getSectorIndex(slf: *const ZkPolygon) -> i16;
}
